---
title: "predicting_westnile"
author: "Camron Pearce, Amy Fox, Alyssa Melvin, Kayla Williams"
date: "November 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(readr)
library(dplyr)
library(lubridate)
library(stringr)
library(leaflet)
library(viridisLite)
library(tidyr)
library(rnoaa)
library(corrplot)

```

```{r}
mosquito_data_original <- read_csv("https://data.cityofchicago.org/api/views/jqe8-8r6s/rows.csv?accessType=DOWNLOAD") 

mosquito_data <- mosquito_data_original %>%
  filter(`SEASON YEAR` %in% c(2016, 2017, 2018)) %>%
  mutate(`TEST DATE` = mdy_hms(`TEST DATE`)) %>%
  rename_all(.funs = str_to_lower) %>%
  rename(year = `season year`, test_id = `test id`, test_date = `test date`,
         number_mosquitos = `number of mosquitoes`)

head(mosquito_data)

positive_mosquito <- mosquito_data %>%
  filter(result == "positive")


```

Read in and clean storm data
```{r storm data}
storms_2016 <- read_csv("../data/StormEvents_details-ftp_v1.0_d2016_c20180718.csv") 

storms_2017 <- read_csv("../data/StormEvents_details-ftp_v1.0_d2017_c20181017.csv")

storms_2018 <- read_csv("../data/StormEvents_details-ftp_v1.0_d2018_c20181017.csv")

all_storm <- rbind(storms_2016, storms_2017, storms_2018) %>%
  rename_all(.funs = str_to_lower) %>%
  filter(state == "ILLINOIS" & cz_name == "COOK") %>%
  mutate(date = begin_date_time) %>%
  select(date, event_type, begin_lat, begin_lon, end_lat, end_lon) %>%
  mutate(date = dmy_hms(date)) %>%
  mutate(week = week(date), 
         year = year(date)) %>%
  filter(month(date) > 4 & month(date) < 11)

head(all_storm)


#Remove double events 
storm_events <- unique(all_storm[c("year", "week", "event_type")])
  
```

Add interactive feature with number of positive or negative mosquitos found
```{r}

pal <- colorFactor(viridis(2), mosquito_data$result)

popup_info <- paste0("<b>Time<b>", mosquito_data$test_date,
                     "<b>Case<b>", mosquito_data$result)

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = mosquito_data, radius = 2, lng = ~longitude, lat = ~latitude, 
                   color = pal(mosquito_data$result), opacity = 0.9, group = "mosquito", popup = popup_info) %>% 
  addCircleMarkers(data = mosquito_data, radius = 2, lng = ~longitude, lat = ~latitude, 
                   color = pal(positive_mosquito$result), opacity = 0.9, group = "positive mosquito") %>%
  addLegend(pal = pal, values = mosquito_data$result, opacity = 0.9) %>%
  addLayersControl(baseGroups = c("base map"),
                   overlayGroups = c("mosquito", "positive mosquito"))
  
```



```{r, st. charles soil data}
soil_2017 <- read.delim("https://www.isws.illinois.edu/warm/data/cdfs/stcday.txt") %>% 
  filter(year %in% c(2016, 2017)) %>%
  select(year, month, day,
         avg_soiltemp_4in_sod, avg_soiltemp_2in_bare) %>% 
  unite(date, month, day, year, sep = "-") %>% 
  mutate(date = mdy(date)) %>% 
  mutate(week = week(date)) %>% 
  mutate(year = year(date)) %>%
  filter(month(date) > 4 & month(date) < 11) %>%
  na.omit()

soil_2018 <- 
  read.delim("https://www.isws.illinois.edu/warm/data/cdfs/current/stcday18.txt") %>% 
  select(year, month, day,
         avg_soiltemp_4in_sod, avg_soiltemp_2in_bare) %>% 
  unite(date, month, day, year, sep = "-") %>% 
  mutate(date = mdy(date)) %>% 
  slice(-1) %>% 
  mutate(week = week(date)) %>% 
  mutate(year = year(date)) %>%
  filter(month(date) > 4 & month(date) < 11) %>%
  na.omit()

all_soil_temps <-
  rbind(soil_2017, soil_2018) %>% 
  mutate(avg_soiltemp_4in_sod = as.numeric(as.character(avg_soiltemp_4in_sod))) %>%
  mutate(avg_soiltemp_2in_bare = as.numeric(as.character(avg_soiltemp_2in_bare))) %>%
  group_by(year, week) %>% 
  summarise(avg_soil_t_4 = mean(avg_soiltemp_4in_sod, na.rm = TRUE),
            avg_soil_t_2 = mean(avg_soiltemp_2in_bare, na.rm = TRUE))

head(all_soil_temps)


tail(all_soil_temps)

```



```{r weather}


weather_data <- read_csv("../data/weather_data.csv") %>% 
  rename(station = "STATION",
         name = "NAME",
         date = "DATE",
         wind_speed = "AWND",
         precip = "PRCP") %>% 
  mutate(week = week(date)) %>% 
  mutate(year = year(date)) %>%
  filter(month(date) > 4 & month(date) < 11)

colnames(weather_data)

#works for all?
weather_data %>% 
  group_by(year, week) %>% 
  summarise(precip_mean = mean(precip, na.rm = TRUE)) %>% 
  ungroup()
```


```{r}

all_data <- full_join(mosquito_data, storm_events)
all_data <- full_join(all_data, all_soil_temps)
all_data <- full_join(all_data, weather_data)


head(all_data)

```


Correlation matrix using correlogram (in works until joined dataset available)

```{r}
#correlation <- cor()
#corrplot(x, method = "number")
```



